<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticIniteb415076a2361694727e6673326be122
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MRK_Rest_Permissions\\' => 21,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MRK_Rest_Permissions\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticIniteb415076a2361694727e6673326be122::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticIniteb415076a2361694727e6673326be122::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticIniteb415076a2361694727e6673326be122::$classMap;

        }, null, ClassLoader::class);
    }
}
